// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkRgeD86n7V0aTh47-Kr5jr806AAvh6TU',
    appId: '1:898332310060:web:23606845d601e63de92f89',
    messagingSenderId: '898332310060',
    projectId: 'gestionbiomedica-b09c6',
    authDomain: 'gestionbiomedica-b09c6.firebaseapp.com',
    storageBucket: 'gestionbiomedica-b09c6.firebasestorage.app',
    measurementId: 'G-EFX7HWVS6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjXVGkbNOx9Sr6KJ4qxbkU1N_X6zpOmVo',
    appId: '1:898332310060:android:7023b2ae2f1f0609e92f89',
    messagingSenderId: '898332310060',
    projectId: 'gestionbiomedica-b09c6',
    storageBucket: 'gestionbiomedica-b09c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI3qvhrQGEy4stBvZgm5PNrH2xHf7Gv4c',
    appId: '1:898332310060:ios:8c7c6f3afb1f4665e92f89',
    messagingSenderId: '898332310060',
    projectId: 'gestionbiomedica-b09c6',
    storageBucket: 'gestionbiomedica-b09c6.firebasestorage.app',
    iosBundleId: 'com.example.proyect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI3qvhrQGEy4stBvZgm5PNrH2xHf7Gv4c',
    appId: '1:898332310060:ios:8c7c6f3afb1f4665e92f89',
    messagingSenderId: '898332310060',
    projectId: 'gestionbiomedica-b09c6',
    storageBucket: 'gestionbiomedica-b09c6.firebasestorage.app',
    iosBundleId: 'com.example.proyect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkRgeD86n7V0aTh47-Kr5jr806AAvh6TU',
    appId: '1:898332310060:web:9e8e4abeae655421e92f89',
    messagingSenderId: '898332310060',
    projectId: 'gestionbiomedica-b09c6',
    authDomain: 'gestionbiomedica-b09c6.firebaseapp.com',
    storageBucket: 'gestionbiomedica-b09c6.firebasestorage.app',
    measurementId: 'G-3F8G5NCJDK',
  );
}
